### PR TITLE
:art: list pretty printing

### LINKED ISSUE #114: List doesn't work when message limit is exceeded
Also add pretty printing

### PR DESCRIPTION
**Pull request by nothingelsematters**
Closes #114

### CODE REVIEW

File: src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/testcontainers/ListingTest.kt [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+            - $listMembers
+              ├── `${aliasName.toLowerCase()}`
+              └── `${partyName.toLowerCase()}`
+            - $secondPartyMembers
+              └── `$secondPartyName`
+        """.trimIndent()
+    }
+
+    @Test
+    fun `a horses herd list test`() {
```
Comment (ShuffleZZZ) [inline src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/testcontainers/ListingTest.kt:77]: KEKW

File: src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/testcontainers/ListingTest.kt [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+        val partyNames = mutableListOf<String>()
+
+        -"/create $partyName $members"
+
+        for (i in 0..100) {
+            val currentPartyName = "${"cheval".repeat(7)}-$i"
```
Comment (ShuffleZZZ) [inline src/test/kotlin/com/github/pool_party/pull_party_bot/commands/handlers/testcontainers/ListingTest.kt:83]: 🐎🐎🐎

**Review by ShuffleZZZ — APPROVED** [review]
